import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateReport = (report) => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235);
  doc.text("GymPro Management Report", 14, 20);

  // Subtitle
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(
    `Generated on : ${new Date().toLocaleDateString()}`,
    14,
    30
  );

  // Table
  autoTable(doc, {
    startY: 40,
    head: [["Metric", "Value"]],
    body: [
      ["Total Members", report.total_members],
      ["Membership Plans", report.total_plans],
      ["Total Revenue", `₹${report.total_revenue}`],
      ["Today's Attendance", report.today_attendance],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [37, 99, 235],
    },
  });

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    "Generated by GymPro Management System",
    14,
    doc.internal.pageSize.height - 10
  );

  doc.save("Gym_Report.pdf");
};